
build: CallTheManager.class

CallTheManager.class: CallTheManager.java
	javac CallTheManager.java

run: CallTheManager.class
	java -cp .:sqlite-jdbc-3.39.3.0.jar CallTheManager

clean:
	rm CallTheManager.class
